package Forms;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
// import javax.swing.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.awt.*;
import javax.swing.*;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author paps
 */
public class LoginForm extends JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setTitle("Login");
        this.setVisible(true);
        this.setSize(450, 150);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        centerFrame(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        passwordLbl = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        usernameLbl.setText("username :");

        passwordLbl.setText("password :");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(usernameLbl,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 81,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(usernameInput)
                                                        .addComponent(passwordInput,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 331,
                                                                Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LoginButton)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLbl)
                                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(passwordInput)
                                        .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>

    private void openMainForm() {
        MainForm mainForm = new MainForm();
        mainForm.setVisible(true);
    }

    private void LoginButtonActionPerformed(ActionEvent e) {
        verifyUser();
    }

    private void verifyUser() {
        String linuxFilePath = "Data/Users.txt";

        String fileLocation = changePath(linuxFilePath);
        // uncomment if using linux
        // String fileLocation = linuxFilePath;

        try (FileReader fileReader = new FileReader(fileLocation);
                BufferedReader bufferedReader = new BufferedReader(fileReader)) {

            // Read each line from the file and print it
            String line;
            boolean notFound = true;
            while ((line = bufferedReader.readLine()) != null) {
                String[] data = line.split(" ");

                String username = data[0];
                String password = data[1];
                String realPassword = new String(passwordInput.getPassword());

                if (username.equals(usernameInput.getText()) && password.equals(realPassword)) {
                    notFound = false;
                    JOptionPane.showConfirmDialog(this, "succesfully logged in ", "Login", JOptionPane.DEFAULT_OPTION);
                    this.dispose();
                    openMainForm();
                }
            }
            if (notFound) {
                JOptionPane.showMessageDialog(this, "error");
                passwordInput.setText("");
            }

        } catch (IOException e) {
            // Handle IOException (e.g., file not found or permission issues)
            e.printStackTrace();
        }
    }

    // changes linux path to a windows path
    private String changePath(String LinuxFilePath) {
        Path linuxPath = Paths.get(LinuxFilePath);

        Path windowsPath = linuxPath.toAbsolutePath().normalize();
        String windowsFilePath = windowsPath.toString();

        return windowsFilePath;

    }

    // myVariables

    // Variables declaration - do not modify
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration

    // test GUI
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LoginForm form = new LoginForm();
        });
    }

    private void centerFrame(JFrame fr) {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = fr.getSize().width;
        int h = fr.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        fr.setLocation(x, y);
    }

}
