package Forms;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author paps
 */
public class ReservationForm extends javax.swing.JFrame {

        private void centerFrame(JFrame fr) {
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                int w = fr.getSize().width;
                int h = fr.getSize().height;
                int x = (dim.width - w) / 2;
                int y = (dim.height - h) / 2;

                fr.setLocation(x, y);
        }

        /**
         * Creates new form ReservationForm
         */
        public ReservationForm() {
                initComponents();
                this.setResizable(false);
                this.addWindowListener(new WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                                Reseption reseption = new Reseption();
                                reseption.setVisible(true);
                                centerFrame(reseption);
                        }
                });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jTextField7 = new javax.swing.JTextField();
                jTextField10 = new javax.swing.JTextField();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                oldSearchBar = new javax.swing.JTextField();
                oldCustomerComboBox = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                oldRoomsComboBox = new javax.swing.JComboBox<>();
                jLabel2 = new javax.swing.JLabel();
                oldDateInput = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                oldDurationInput = new javax.swing.JTextField();
                oldReserveButton = new javax.swing.JButton();
                oldCancelButton = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                newNameInput = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                newSurnameInput = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                newIDInput = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                newDateInput = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                newDurationInput = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                newRoomsComboBox = new javax.swing.JComboBox<>();
                jLabel10 = new javax.swing.JLabel();
                newReserveButton = new javax.swing.JButton();
                newCancelButton = new javax.swing.JButton();

                showCustomerNames();
                showRoomsForComboBox(oldRoomsComboBox);
                showRoomsForComboBox(newRoomsComboBox);

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Make Reservation");

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("ROOM : ");

                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("DATE :");

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("DURATION :");

                oldReserveButton.setText("RESERVE");
                oldReserveButton.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                                if (oldDateInput.getText().equals("") || oldDurationInput.getText().equals("")) {
                                        JOptionPane.showMessageDialog(null, "Please fill all the fields", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                        return;

                                } else {
                                        oldReserveButtonActionPerformed(evt);
                                }
                        }
                });

                oldCancelButton.setText("CANCEL");
                oldCancelButton.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                                dispose();
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(oldCustomerComboBox, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(oldSearchBar)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                60,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(oldDateInput)
                                                                                                                .addComponent(oldRoomsComboBox,
                                                                                                                                0,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(oldDurationInput)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(oldReserveButton,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                135,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(oldCancelButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                131,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(oldSearchBar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(oldCustomerComboBox,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(oldDateInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(oldDurationInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(oldRoomsComboBox,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                65,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(oldReserveButton)
                                                                                .addComponent(oldCancelButton))
                                                                .addGap(34, 34, 34)));

                jTabbedPane1.addTab("Old Customer", jPanel1);

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setText("NAME :");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("SURNAME :");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("ID :");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("DATE :");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("DURATION :");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel9.setText("ROOM : ");

                jLabel10.setText("write the date as follow 2023-12-19");

                newReserveButton.setText("RESERVE");
                newReserveButton.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                                if (newNameInput.getText().equals("") || newSurnameInput.getText().equals("")
                                                || newIDInput.getText().equals("") || newDateInput.getText().equals("")
                                                || newDurationInput.getText().equals("")
                                                || newRoomsComboBox.getSelectedItem().toString().equals("")) {
                                        JOptionPane.showMessageDialog(null, "Please fill all the fields", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                        return;
                                } else {
                                        newReserveRoom();
                                }
                        }
                });

                newCancelButton.setText("CANCEL");
                newCancelButton.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                                dispose();
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel10,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                57,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(newNameInput,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                215,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel8,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                57,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(6, 6, 6)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(newSurnameInput)
                                                                                                                .addComponent(newIDInput)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel9,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel6,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                57,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(newRoomsComboBox)
                                                                                                                .addComponent(newDateInput)
                                                                                                                .addComponent(newDurationInput)))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(newReserveButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                122,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(newCancelButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                122,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(newNameInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(newSurnameInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(newIDInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel4))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel10)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(newDateInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(newDurationInput,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(newRoomsComboBox,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(newReserveButton)
                                                                                .addComponent(newCancelButton))
                                                                .addContainerGap(38, Short.MAX_VALUE)));

                jTabbedPane1.addTab("New Customer", jPanel2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1));

                pack();
        }// </editor-fold>

        private void newReserveRoom() {
                LocalDate[] dates = getDates(newDateInput, newDurationInput);
                String customerData = getCustomerData(newNameInput, newSurnameInput, newIDInput);
                String roomData = getRoomData(newRoomsComboBox);
                String duration = getDurationOfStay(newDurationInput);

                String[] customerParts = customerData.split(" ");
                String[] roomParts = roomData.split(" ");

                String customerName = customerParts[0];
                String customerSurname = customerParts[1];
                String customerID = customerParts[2];
                String roomNumber = roomParts[0];

                try (BufferedReader br = new BufferedReader(new FileReader("Data/Reservations.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(" ");
                                if (parts.length > 1) {
                                        String room = parts[3];
                                        if (room.equals(roomNumber)) {
                                                JOptionPane.showMessageDialog(null, "Room is already reserved");
                                                return;
                                        }
                                }
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                }

                try (PrintWriter pw = new PrintWriter(new FileWriter("Data/Reservations.txt", true))) {
                        // add the duration to the reservation.txt file
                        pw.println(customerName + " " + customerSurname + " " + customerID + " " + roomNumber + " "
                                        + duration + " " + dates[0]
                                        + " " + dates[1]);
                        updateCustomer();
                        JOptionPane.showMessageDialog(null, "Room reserved and new customer added", roomNumber,
                                        JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                } catch (IOException e) {
                        e.printStackTrace();
                }
        }

        private void oldReserveButtonActionPerformed(ActionEvent evt) {
                oldReserveRoom();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ReservationForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ReservationForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ReservationForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ReservationForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ReservationForm().setVisible(true);
                        }
                });
        }

        private void showCustomerNames() {
                String searchText = oldSearchBar.getText();
                oldCustomerComboBox.removeAllItems();
                try (BufferedReader br = new BufferedReader(new FileReader("Data/Customers.txt"))) {
                        // Read all reservations into a HashSet
                        HashSet<String> reservedCustomers = new HashSet<>();
                        try (BufferedReader br2 = new BufferedReader(new FileReader("Data/Reservations.txt"))) {
                                String line2;
                                while ((line2 = br2.readLine()) != null) {
                                        String[] parts2 = line2.split(" ");
                                        reservedCustomers.add(parts2[2]);
                                }
                        } catch (IOException e) {
                                e.printStackTrace();
                        }

                        String line;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(" ");
                                if (parts.length > 1 && parts[3].equals("0")) {
                                        if (line.contains(searchText) && !reservedCustomers.contains(parts[2])) { // Check
                                                                                                                  // if
                                                                                                                  // customer
                                                                                                                  // is
                                                                                                                  // in
                                                                                                                  // the
                                                                                                                  // HashSet
                                                oldCustomerComboBox.addItem(parts[0] + " " + parts[1] + " " + parts[2]);
                                        }
                                }
                        }
                } catch (IOException e) {
                        e.printStackTrace();
                }
        }

        private void showRoomsForComboBox(JComboBox<String> JComboBoxRooms) {
                try (BufferedReader br = new BufferedReader(new FileReader("Data/Rooms.txt"))) {
                        try (BufferedReader br2 = new BufferedReader(new FileReader("Data/Reservations.txt"))) {
                                String line;
                                String line2;
                                while ((line = br.readLine()) != null) {
                                        String[] parts = line.split(" ");
                                        if (parts.length > 1) {
                                                String roomNumber = parts[0];
                                                String roomType = parts[1];
                                                String roomStatus = parts[3];

                                                if (roomStatus.equals("0")) {
                                                        boolean isReservable = true;
                                                        while ((line2 = br2.readLine()) != null) {
                                                                String[] parts2 = line2.split(" ");
                                                                if (parts2.length > 1) {
                                                                        String room = parts2[3];
                                                                        if (room.equals(roomNumber)) {
                                                                                isReservable = false;
                                                                                break;
                                                                        }
                                                                }
                                                        }
                                                        if (isReservable) {
                                                                JComboBoxRooms.addItem(roomNumber + " " + roomType);
                                                        }
                                                }
                                        }
                                }
                        } catch (Exception e) {
                                e.printStackTrace();
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        private LocalDate[] getDates(JTextField dateInput, JTextField durationInput) {
                LocalDate[] dates = new LocalDate[2];

                String date = dateInput.getText();
                int duration = Integer.parseInt(durationInput.getText());

                dates[0] = LocalDate.parse(date);
                dates[1] = dates[0].plusDays(duration);

                return dates;
        }

        private String getCustomerData() {
                String customerData = oldCustomerComboBox.getSelectedItem().toString();
                return customerData;
        }

        private String getCustomerData(JTextField nameInput, JTextField surnameInput, JTextField idInput) {
                String name = nameInput.getText();
                String surname = surnameInput.getText();
                String id = idInput.getText();
                String customerData = name + " " + surname + " " + id;
                return customerData;
        }

        private String getRoomData(JComboBox<String> JComboBoxRooms) {
                String roomData = JComboBoxRooms.getSelectedItem().toString();
                return roomData;
        }

        private String getDurationOfStay(JTextField durationInput) {
                String duration = durationInput.getText();
                return duration;
        }

        private void oldReserveRoom() {
                LocalDate[] dates = getDates(oldDateInput, oldDurationInput);
                String customerData = getCustomerData();
                String roomData = getRoomData(oldRoomsComboBox);
                String duration = getDurationOfStay(oldDurationInput);

                String[] customerParts = customerData.split(" ");
                String[] roomParts = roomData.split(" ");

                String customerName = customerParts[0];
                String customerSurname = customerParts[1];
                String customerID = customerParts[2];
                String roomNumber = roomParts[0];

                // Instead, you can only show the rooms that can be reserved in the combo box
                try (BufferedReader br = new BufferedReader(new FileReader("Data/Reservations.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(" ");
                                if (parts.length > 1) {
                                        String room = parts[3];
                                        if (room.equals(roomNumber)) {
                                                JOptionPane.showMessageDialog(null, "Room is already reserved");
                                                return;
                                        }
                                }
                        }
                } catch (Exception e) {
                        e.printStackTrace();
                }

                try (PrintWriter pw = new PrintWriter(new FileWriter("Data/Reservations.txt", true))) {
                        pw.println(customerName + " " + customerSurname + " " + customerID + " " + roomNumber + " "
                                        + duration + " " + dates[0]
                                        + " " + dates[1]);
                        JOptionPane.showMessageDialog(null, "Room reserved successfully", roomNumber,
                                        JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                } catch (IOException e) {
                        e.printStackTrace();
                }
        }

        private void updateCustomer() {
                String name = newNameInput.getText();
                String surname = newSurnameInput.getText();
                String id = newIDInput.getText();
                String roomID = newRoomsComboBox.getSelectedItem().toString().split(" ")[0];

                try (BufferedReader br = new BufferedReader(new FileReader("Data/Customers.txt"))) {
                        String line;
                        boolean customerExists = false;
                        while ((line = br.readLine()) != null) {
                                String[] parts = line.split(" ");
                                if (parts.length > 1) {
                                        if (parts[0].equals(name) || parts[1].equals(surname) && parts[2].equals(id)) {
                                                customerExists = true;
                                                break;
                                        }
                                }
                        }
                        if (customerExists) {
                                JOptionPane.showMessageDialog(null, "Customer already exists", "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        } else {
                                try (PrintWriter writer = new PrintWriter(new FileWriter("Data/Customers.txt", true))) {
                                        // write 0 for the id becaues the room is being reserved
                                        // the other two 0s are for the checkin and checkout dates
                                        writer.println(name + " " + surname + " " + id + " " + "0" + " 0" + " 0");
                                        JOptionPane.showMessageDialog(null, "Customer added and reserved the room",
                                                        "Success",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                } catch (IOException e) {
                                        e.printStackTrace();
                                }
                        }
                } catch (IOException e) {
                        e.printStackTrace();
                }
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextField jTextField10;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JButton newCancelButton;
        private javax.swing.JTextField newDateInput;
        private javax.swing.JTextField newDurationInput;
        private javax.swing.JTextField newIDInput;
        private javax.swing.JTextField newNameInput;
        private javax.swing.JButton newReserveButton;
        private javax.swing.JComboBox<String> newRoomsComboBox;
        private javax.swing.JTextField newSurnameInput;
        private javax.swing.JButton oldCancelButton;
        private javax.swing.JComboBox<String> oldCustomerComboBox;
        private javax.swing.JTextField oldDateInput;
        private javax.swing.JTextField oldDurationInput;
        private javax.swing.JButton oldReserveButton;
        private javax.swing.JComboBox<String> oldRoomsComboBox;
        private javax.swing.JTextField oldSearchBar;
        // End of variables declaration
}